image: Visual Studio 2017
configuration: Release
skip_tags: true

# branches:
#   only:
#     - master
#     - /version.*/
#     - /release.*/
#     - /dev.*/

services:
  - mssql2016

environment:
  assemblyVersion: 1.0.2
  packageVersion: 1.0.2
  access_token:
    secure: IlfmHXRdUK6v8dX/WqieXQ==

cache:
- packages -> appveyor.yml

version: $(assemblyVersion).{build}

init:
- cmd: git config --global core.autocrlf true
- ps: $env:buildVersion = "$env:assemblyVersion.$env:appveyor_build_number"

nuget:
  account_feed: false
  project_feed: false

build_script:
  dotnet build linq2db.EFCore.sln -c Release

before_build:
- ps: |
    if ($env:APPVEYOR_REPO_BRANCH -ne "release")
    {
        $env:packageVersion = "$env:assemblyVersion-rc.$env:appveyor_build_number"
    }

    .\Build\AppVeyor.FixVersionProps.ps1  -path Build\linq2db.Default.props -buildVersion $env:assemblyVersion -nugetVersion $env:packageVersion

- ps: Update-AppveyorBuild -Version $env:buildVersion

after_build:
  dotnet pack .\Source\LinqToDB.EntityFrameworkCore\ -c Release --no-build

test:
  assemblies:
    - '**\*.Tests.dll'

artifacts:
- path: \**\linq2db*.nupkg

deploy:
- provider: NuGet
  server: https://www.myget.org/F/linq2db/api/v2
  api_key:
    secure: LDw0jeA1Yo3R4/TKv2kmlgJR8dTT6Wun2MONq3uDvtVQJG4LOU9LjvVTAc7IgRfm
  skip_symbols: true
  on:
    branch: master

- provider: NuGet
  api_key:
    secure: oTYw2IwTnz4qMD8c/MR/6mo+Nx3wa5Pp8MYfsKBCKCVuU6QCHlj+6QMXpnQses8G
  on:
    branch: release

skip_commits:
  message: /ci skip/      # Regex for matching commit message
